// BuildNG - Nigerian Construction PM Platform
// Constants and configuration

export const CONSTRUCTION_STAGES = [
  {
    id: "foundation",
    name: "Foundation",
    order: 1,
    description: "Setting out, excavation, foundation concrete",
  },
  {
    id: "substructure",
    name: "Substructure",
    order: 2,
    description: "Block work from foundation to DPC level",
  },
  {
    id: "dpc",
    name: "DPC Level",
    order: 3,
    description: "Damp proof course and ground floor slab",
  },
  {
    id: "blockwork",
    name: "Block Work",
    order: 4,
    description: "Superstructure block work to lintel level",
  },
  {
    id: "lintel_roofing",
    name: "Lintel & Roofing",
    order: 5,
    description: "Lintel casting, columns, and roof installation",
  },
  {
    id: "mep",
    name: "MEP Rough-in",
    order: 6,
    description: "Mechanical, electrical, and plumbing first fix",
  },
  {
    id: "finishing",
    name: "Finishing",
    order: 7,
    description: "Plastering, tiling, painting, fixtures",
  },
  {
    id: "handover",
    name: "Handover",
    order: 8,
    description: "Final inspection, cleanup, and handover",
  },
] as const;

export const MATERIAL_CATEGORIES = [
  { id: "cement", name: "Cement", icon: "Package" },
  { id: "steel", name: "Iron & Steel", icon: "Wrench" },
  { id: "sand", name: "Sand", icon: "Mountain" },
  { id: "granite", name: "Granite", icon: "Mountain" },
  { id: "blocks", name: "Blocks", icon: "Square" },
  { id: "roofing", name: "Roofing", icon: "Home" },
  { id: "tiles", name: "Tiles", icon: "Grid3X3" },
  { id: "paint", name: "Paint", icon: "Paintbrush" },
  { id: "plumbing", name: "Plumbing", icon: "Droplets" },
  { id: "electrical", name: "Electrical", icon: "Zap" },
  { id: "doors_windows", name: "Doors & Windows", icon: "DoorOpen" },
  { id: "finishing", name: "Finishing", icon: "Sparkles" },
] as const;

export const ARTISAN_SKILLS = [
  { id: "bricklayer", name: "Bricklayer/Mason", avgDailyRate: 1000000 },
  { id: "tiler", name: "Tiler", avgDailyRate: 1200000 },
  { id: "electrician", name: "Electrician", avgDailyRate: 1500000 },
  { id: "plumber", name: "Plumber", avgDailyRate: 800000 },
  { id: "carpenter", name: "Carpenter", avgDailyRate: 900000 },
  { id: "welder", name: "Welder/Fabricator", avgDailyRate: 1200000 },
  { id: "painter", name: "Painter", avgDailyRate: 700000 },
  { id: "pop_specialist", name: "POP Specialist", avgDailyRate: 1100000 },
  { id: "iron_bender", name: "Iron Bender", avgDailyRate: 1000000 },
  { id: "aluminium", name: "Aluminium Worker", avgDailyRate: 1400000 },
  { id: "ac_tech", name: "AC Technician", avgDailyRate: 1500000 },
  { id: "screeder", name: "Screeder", avgDailyRate: 800000 },
] as const;

export const WARRANTY_PERIODS = {
  roofing: { component: "Roofing", years: 5 },
  plumbing: { component: "Plumbing", years: 2 },
  electrical: { component: "Electrical", years: 2 },
  structural: { component: "Structural", years: 10 },
  painting: { component: "Paint/Finishing", years: 1 },
  windows_doors: { component: "Windows & Doors", years: 3 },
  mep: { component: "MEP Systems", years: 2 },
  waterproofing: { component: "Waterproofing", years: 5 },
} as const;

export const ESCROW_FEE_PERCENT = 2.5;
export const GROUP_BUY_COMMISSION_PERCENT = 3.5;
export const INSPECTION_FEE_PER_STAGE_KOBO = 15000000; // ₦150,000
export const PLATFORM_PLANS = {
  starter: {
    name: "Starter",
    priceKobo: 0,
    projects: 1,
    teamMembers: 1,
  },
  professional: {
    name: "Professional",
    priceKobo: 2500000,
    projects: -1,
    teamMembers: 5,
  },
  enterprise: {
    name: "Enterprise",
    priceKobo: 15000000,
    projects: -1,
    teamMembers: -1,
  },
} as const;

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const MAJOR_CITIES: Record<string, string[]> = {
  Lagos: [
    "Lekki",
    "Victoria Island",
    "Ikoyi",
    "Banana Island",
    "Ajah",
    "Ikeja",
    "Surulere",
    "Yaba",
    "Maryland",
    "Magodo",
    "Gbagada",
    "Ogba",
    "Festac",
    "Apapa",
    "Epe",
    "Ikorodu",
    "Badagry",
  ],
  "FCT Abuja": [
    "Maitama",
    "Wuse",
    "Garki",
    "Jabi",
    "Asokoro",
    "Gwarinpa",
    "Kubwa",
    "Lugbe",
    "Dei-Dei",
    "Karu",
    "Nyanya",
    "Dutse",
  ],
  Rivers: [
    "Port Harcourt",
    "Obio-Akpor",
    "Eleme",
    "Bonny",
    "Trans Amadi",
    "GRA PH",
    "Rumuola",
  ],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota", "Ilaro", "Sango"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki"],
  Enugu: ["Enugu", "Nsukka", "Agbani", "Emene"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Effurun"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Wudil", "Gwarzo"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
};

export const STATUS_COLORS: Record<string, string> = {
  active: "bg-emerald-100 text-emerald-800",
  completed: "bg-blue-100 text-blue-800",
  pending: "bg-amber-100 text-amber-800",
  in_progress: "bg-cyan-100 text-cyan-800",
  disputed: "bg-red-100 text-red-800",
  cancelled: "bg-gray-100 text-gray-800",
  draft: "bg-slate-100 text-slate-800",
  verified: "bg-green-100 text-green-800",
  approved: "bg-emerald-100 text-emerald-800",
  rejected: "bg-red-100 text-red-800",
  critical: "bg-red-100 text-red-800",
  high: "bg-orange-100 text-orange-800",
  medium: "bg-yellow-100 text-yellow-800",
  low: "bg-green-100 text-green-800",
};

export const NAV_ITEMS = [
  {
    label: "Dashboard",
    href: "/dashboard",
    icon: "LayoutDashboard",
    section: "OVERVIEW",
  },
  {
    label: "Escrow",
    href: "/dashboard/escrow",
    icon: "Shield",
    section: "PRODUCTS",
    badge: 8,
  },
  {
    label: "Materials",
    href: "/dashboard/materials",
    icon: "Package",
    section: "PRODUCTS",
    badge: 5,
  },
  {
    label: "Quality",
    href: "/dashboard/quality",
    icon: "ClipboardCheck",
    section: "PRODUCTS",
    badge: 3,
  },
  {
    label: "Estates",
    href: "/dashboard/estates",
    icon: "Building2",
    section: "PRODUCTS",
    badge: 4,
  },
  {
    label: "Artisans",
    href: "/dashboard/artisans",
    icon: "Users",
    section: "PRODUCTS",
    badge: 12,
  },
  {
    label: "Permits",
    href: "/dashboard/permits",
    icon: "FileCheck",
    section: "PRODUCTS",
    badge: 2,
  },
  {
    label: "Defects",
    href: "/dashboard/defects",
    icon: "AlertTriangle",
    section: "PRODUCTS",
    badge: 6,
  },
  {
    label: "Market",
    href: "/dashboard/market",
    icon: "TrendingUp",
    section: "INSIGHTS",
  },
  {
    label: "Reports",
    href: "/dashboard/reports",
    icon: "BarChart3",
    section: "INSIGHTS",
  },
  {
    label: "Settings",
    href: "/dashboard/settings",
    icon: "Settings",
    section: "ACCOUNT",
  },
  {
    label: "Help",
    href: "/dashboard/help",
    icon: "HelpCircle",
    section: "ACCOUNT",
  },
] as const;
