export const mockUsers = [
  { id: "u1", name: "Chioma Okafor", email: "chioma@email.com", phone: "+234 801 234 5678", role: "CLIENT" as const, state: "Lagos", city: "Lekki", company: "Okafor Holdings", ninVerified: true },
  { id: "u2", name: "Adebayo Williams", email: "adebayo@construction.ng", phone: "+234 802 345 6789", role: "CONTRACTOR" as const, state: "Lagos", city: "Ikeja", company: "Adebayo Construction Ltd", ninVerified: true },
  { id: "u3", name: "Kelechi Eze", email: "kelechi@engineers.ng", phone: "+234 803 456 7890", role: "ENGINEER" as const, state: "Lagos", city: "VI", company: "KE Structural Engineers", ninVerified: true },
  { id: "u4", name: "Fatima Mohammed", email: "fatima@estates.ng", phone: "+234 804 567 8901", role: "DEVELOPER" as const, state: "FCT Abuja", city: "Maitama", company: "Royal Gardens Development", ninVerified: true },
  { id: "u5", name: "Emeka Nwosu", email: "emeka@build.ng", phone: "+234 805 678 9012", role: "CONTRACTOR" as const, state: "Lagos", city: "Ajah", company: "Nwosu & Sons Construction", ninVerified: true },
  { id: "u6", name: "Aisha Bello", email: "aisha@design.ng", phone: "+234 806 789 0123", role: "ENGINEER" as const, state: "FCT Abuja", city: "Wuse", company: "AB Design Studio", ninVerified: true },
  { id: "u7", name: "Tunde Bakare", email: "tunde@homes.ng", phone: "+234 807 890 1234", role: "CLIENT" as const, state: "Lagos", city: "Magodo", ninVerified: true },
  { id: "u8", name: "Ngozi Chukwuma", email: "ngozi@estates.ng", phone: "+234 808 901 2345", role: "ESTATE_MANAGER" as const, state: "Lagos", city: "Lekki", company: "Emerald City Management", ninVerified: true },
  { id: "u9", name: "Ibrahim Danladi", email: "ibrahim@build.ng", phone: "+234 809 012 3456", role: "ARTISAN" as const, state: "FCT Abuja", city: "Dei-Dei", ninVerified: true },
  { id: "u10", name: "Segun Ogundimu", email: "segun@invest.ng", phone: "+234 810 123 4567", role: "CLIENT" as const, state: "Lagos", city: "Ikoyi", company: "Ogundimu Investments", ninVerified: true },
];

export const mockEscrowProjects = [
  {
    id: "esc1",
    reference: "NGP-ESC-2024-0042",
    title: "4-Bedroom Duplex, Lekki Phase 1",
    client: mockUsers[0],
    contractor: mockUsers[1],
    engineer: mockUsers[2],
    totalAmountKobo: 5200000000,
    releasedAmountKobo: 2800000000,
    status: "ACTIVE" as const,
    state: "Lagos",
    city: "Lekki",
    createdAt: "2024-01-15",
    milestones: [
      { id: "m1", name: "Foundation", amountKobo: 800000000, status: "RELEASED" as const, orderIndex: 1, verifiedAt: "2024-02-12" },
      { id: "m2", name: "Block Work to DPC", amountKobo: 600000000, status: "RELEASED" as const, orderIndex: 2, verifiedAt: "2024-03-05" },
      { id: "m3", name: "Block Work to Lintel", amountKobo: 700000000, status: "RELEASED" as const, orderIndex: 3, verifiedAt: "2024-04-18" },
      { id: "m4", name: "Roofing", amountKobo: 1000000000, status: "IN_PROGRESS" as const, orderIndex: 4 },
      { id: "m5", name: "MEP First Fix", amountKobo: 800000000, status: "PENDING" as const, orderIndex: 5 },
      { id: "m6", name: "Plastering & Finishing", amountKobo: 700000000, status: "PENDING" as const, orderIndex: 6 },
      { id: "m7", name: "Final Handover", amountKobo: 600000000, status: "PENDING" as const, orderIndex: 7 },
    ],
  },
  {
    id: "esc2",
    reference: "NGP-ESC-2024-0058",
    title: "3-Storey Commercial Building, Victoria Island",
    client: mockUsers[9],
    contractor: mockUsers[4],
    engineer: mockUsers[2],
    totalAmountKobo: 15000000000,
    releasedAmountKobo: 6500000000,
    status: "ACTIVE" as const,
    state: "Lagos",
    city: "Victoria Island",
    createdAt: "2024-02-01",
    milestones: [
      { id: "m8", name: "Foundation & Piling", amountKobo: 3000000000, status: "RELEASED" as const, orderIndex: 1, verifiedAt: "2024-04-10" },
      { id: "m9", name: "Ground Floor Structure", amountKobo: 2500000000, status: "RELEASED" as const, orderIndex: 2, verifiedAt: "2024-06-20" },
      { id: "m10", name: "First Floor Structure", amountKobo: 2500000000, status: "IN_PROGRESS" as const, orderIndex: 3 },
      { id: "m11", name: "Second Floor & Roof", amountKobo: 3000000000, status: "PENDING" as const, orderIndex: 4 },
      { id: "m12", name: "MEP & Finishing", amountKobo: 2500000000, status: "PENDING" as const, orderIndex: 5 },
      { id: "m13", name: "Handover", amountKobo: 1500000000, status: "PENDING" as const, orderIndex: 6 },
    ],
  },
  {
    id: "esc3",
    reference: "NGP-ESC-2024-0071",
    title: "5-Bedroom Mansion, Banana Island",
    client: mockUsers[9],
    contractor: mockUsers[1],
    engineer: mockUsers[5],
    totalAmountKobo: 25000000000,
    releasedAmountKobo: 25000000000,
    status: "COMPLETED" as const,
    state: "Lagos",
    city: "Banana Island",
    createdAt: "2023-06-01",
    milestones: [],
  },
  {
    id: "esc4",
    reference: "NGP-ESC-2024-0089",
    title: "Semi-Detached Duplex, Jabi",
    client: mockUsers[6],
    contractor: mockUsers[4],
    engineer: mockUsers[5],
    totalAmountKobo: 4500000000,
    releasedAmountKobo: 0,
    status: "FUNDED" as const,
    state: "FCT Abuja",
    city: "Jabi",
    createdAt: "2024-05-10",
    milestones: [],
  },
  {
    id: "esc5",
    reference: "NGP-ESC-2024-0095",
    title: "Bungalow Renovation, GRA Ikeja",
    client: mockUsers[6],
    contractor: mockUsers[1],
    engineer: mockUsers[2],
    totalAmountKobo: 1800000000,
    releasedAmountKobo: 600000000,
    status: "DISPUTED" as const,
    state: "Lagos",
    city: "Ikeja",
    createdAt: "2024-03-20",
    milestones: [],
  },
];

export const mockMaterialPrices = [
  { id: "mp1", name: "Dangote Cement 50kg", brand: "Dangote", category: "Cement", city: "Lagos", priceKobo: 650000, changePercent: 2.1, unit: "bag" },
  { id: "mp2", name: "Dangote Cement 50kg", brand: "Dangote", category: "Cement", city: "Abuja", priceKobo: 620000, changePercent: -1.5, unit: "bag" },
  { id: "mp3", name: "BUA Cement 50kg", brand: "BUA", category: "Cement", city: "Lagos", priceKobo: 600000, changePercent: 0.8, unit: "bag" },
  { id: "mp4", name: "12mm Rebar", brand: "Various", category: "Steel", city: "Lagos", priceKobo: 35000000, changePercent: -3.2, unit: "ton" },
  { id: "mp5", name: "12mm Rebar", brand: "Various", category: "Steel", city: "Abuja", priceKobo: 33500000, changePercent: -2.8, unit: "ton" },
  { id: "mp6", name: "Sharp Sand", brand: "N/A", category: "Sand", city: "Lagos", priceKobo: 5500000, changePercent: 5.0, unit: "trip" },
  { id: "mp7", name: "Granite 3/4\"", brand: "N/A", category: "Granite", city: "Lagos", priceKobo: 14000000, changePercent: 1.2, unit: "trip" },
  { id: "mp8", name: "9-inch Block", brand: "Various", category: "Blocks", city: "Lagos", priceKobo: 50000, changePercent: 0, unit: "piece" },
  { id: "mp9", name: "0.55mm Roofing Sheet", brand: "Various", category: "Roofing", city: "Lagos", priceKobo: 600000, changePercent: -1.0, unit: "sheet" },
  { id: "mp10", name: "60x60 Floor Tiles", brand: "Various", category: "Tiles", city: "Lagos", priceKobo: 1200000, changePercent: 0.5, unit: "carton" },
  { id: "mp11", name: "Dulux Emulsion 20L", brand: "Dulux", category: "Paint", city: "Lagos", priceKobo: 3500000, changePercent: 3.0, unit: "bucket" },
  { id: "mp12", name: "2.5mm Cable (100m)", brand: "Cutix", category: "Electrical", city: "Lagos", priceKobo: 4500000, changePercent: -0.5, unit: "roll" },
  { id: "mp13", name: "PPR Pipe 1\" (4m)", brand: "Various", category: "Plumbing", city: "Lagos", priceKobo: 350000, changePercent: 1.8, unit: "length" },
  { id: "mp14", name: "Steel Security Door", brand: "Various", category: "Doors", city: "Lagos", priceKobo: 12000000, changePercent: 0, unit: "piece" },
  { id: "mp15", name: "POP Cement 40kg", brand: "Various", category: "Finishing", city: "Lagos", priceKobo: 500000, changePercent: 2.5, unit: "bag" },
];

export const mockArtisans = [
  { id: "a1", name: "Musa Ibrahim", primarySkill: "Bricklayer", skills: ["Bricklaying", "Plastering", "Screeding"], yearsExperience: 15, dailyRateKobo: 1000000, rating: 4.8, totalReviews: 87, location: "Surulere, Lagos", state: "Lagos", city: "Surulere", available: true, ninVerified: true },
  { id: "a2", name: "Chinedu Obi", primarySkill: "Electrician", skills: ["Wiring", "Panel Installation", "Generator Setup"], yearsExperience: 8, dailyRateKobo: 1500000, rating: 4.6, totalReviews: 45, location: "Wuse, Abuja", state: "FCT Abuja", city: "Wuse", available: true, ninVerified: true },
  { id: "a3", name: "Sunday Adeyemi", primarySkill: "Tiler", skills: ["Floor Tiling", "Wall Tiling", "Marble Work"], yearsExperience: 12, dailyRateKobo: 1200000, rating: 4.9, totalReviews: 92, location: "Lekki, Lagos", state: "Lagos", city: "Lekki", available: false, ninVerified: true },
  { id: "a4", name: "Yakubu Sani", primarySkill: "Plumber", skills: ["Pipe Installation", "Drainage", "Water Heater"], yearsExperience: 10, dailyRateKobo: 800000, rating: 4.4, totalReviews: 38, location: "Garki, Abuja", state: "FCT Abuja", city: "Garki", available: true, ninVerified: true },
  { id: "a5", name: "Blessing Eze", primarySkill: "Painter/POP", skills: ["Painting", "POP Ceiling", "Screeding"], yearsExperience: 6, dailyRateKobo: 700000, rating: 4.7, totalReviews: 55, location: "Ajah, Lagos", state: "Lagos", city: "Ajah", available: true, ninVerified: true },
  { id: "a6", name: "Abdullahi Musa", primarySkill: "Welder", skills: ["Gate Fabrication", "Burglar Proof", "Staircase"], yearsExperience: 20, dailyRateKobo: 1200000, rating: 4.5, totalReviews: 67, location: "Dei-Dei, Abuja", state: "FCT Abuja", city: "Dei-Dei", available: true, ninVerified: true },
  { id: "a7", name: "Tunde Bakare", primarySkill: "Carpenter", skills: ["Roofing", "Door Frames", "Built-in Wardrobes"], yearsExperience: 14, dailyRateKobo: 900000, rating: 4.3, totalReviews: 41, location: "Ikeja, Lagos", state: "Lagos", city: "Ikeja", available: false, ninVerified: true },
  { id: "a8", name: "Emmanuel Nwachukwu", primarySkill: "Iron Bender", skills: ["Column Reinforcement", "Slab Reinforcement", "Foundation"], yearsExperience: 11, dailyRateKobo: 1000000, rating: 4.6, totalReviews: 53, location: "PH, Rivers", state: "Rivers", city: "Port Harcourt", available: true, ninVerified: true },
  { id: "a9", name: "Kola Adesanya", primarySkill: "Aluminium", skills: ["Windows", "Doors", "Cladding", "Glass Work"], yearsExperience: 9, dailyRateKobo: 1400000, rating: 4.7, totalReviews: 36, location: "VI, Lagos", state: "Lagos", city: "Victoria Island", available: true, ninVerified: true },
  { id: "a10", name: "Ibrahim Danladi", primarySkill: "POP Specialist", skills: ["POP Ceiling", "Cornice", "Wall Screeding"], yearsExperience: 7, dailyRateKobo: 1100000, rating: 4.8, totalReviews: 48, location: "Maitama, Abuja", state: "FCT Abuja", city: "Maitama", available: true, ninVerified: true },
  { id: "a11", name: "Ade Johnson", primarySkill: "Master Tiler", skills: ["Porcelain", "Marble", "Mosaic", "Swimming Pool"], yearsExperience: 18, dailyRateKobo: 1800000, rating: 5.0, totalReviews: 120, location: "Ikoyi, Lagos", state: "Lagos", city: "Ikoyi", available: false, ninVerified: true },
  { id: "a12", name: "Victor Okonkwo", primarySkill: "General Mason", skills: ["Block Work", "Plastering", "Foundation"], yearsExperience: 13, dailyRateKobo: 750000, rating: 4.2, totalReviews: 29, location: "Enugu", state: "Enugu", city: "Enugu", available: true, ninVerified: true },
];

export const mockEstates = [
  { id: "e1", name: "Royal Gardens Estate", address: "Chevron Drive, Lekki, Lagos", state: "Lagos", city: "Lekki", totalUnits: 50, completedUnits: 18, inProgressUnits: 22, notStartedUnits: 10, totalValueKobo: 320000000000, completionPercent: 72, health: "On Track" as const },
  { id: "e2", name: "Emerald City", address: "Abraham Adesanya, Ajah, Lagos", state: "Lagos", city: "Ajah", totalUnits: 30, completedUnits: 5, inProgressUnits: 15, notStartedUnits: 10, totalValueKobo: 180000000000, completionPercent: 45, health: "At Risk" as const },
  { id: "e3", name: "Jabi Luxury Villas", address: "Jabi Lake Road, Jabi, Abuja", state: "FCT Abuja", city: "Jabi", totalUnits: 20, completedUnits: 14, inProgressUnits: 5, notStartedUnits: 1, totalValueKobo: 210000000000, completionPercent: 88, health: "On Track" as const },
  { id: "e4", name: "Wuse Heights", address: "Aminu Kano Crescent, Wuse 2, Abuja", state: "FCT Abuja", city: "Wuse", totalUnits: 27, completedUnits: 6, inProgressUnits: 14, notStartedUnits: 7, totalValueKobo: 135000000000, completionPercent: 55, health: "Behind" as const },
];

export const mockPermitApplications = [
  { id: "p1", reference: "LASBCA-2024-0847", title: "Building Plan Approval - Lekki Phase 1", type: "BUILDING_PLAN" as const, regulatoryBody: "LASBCA", status: "UNDER_REVIEW" as const, currentStep: 4, totalSteps: 7, totalFeeKobo: 75000000, paidFeeKobo: 20000000, submittedAt: "2024-03-01" },
  { id: "p2", reference: "LASEPA-2024-0312", title: "Environmental Impact - Banana Island", type: "ENVIRONMENTAL" as const, regulatoryBody: "LASEPA", status: "DOCUMENTS_REQUESTED" as const, currentStep: 2, totalSteps: 5, totalFeeKobo: 35000000, paidFeeKobo: 15000000, submittedAt: "2024-04-15" },
  { id: "p3", reference: "FCDA-2024-1205", title: "Foundation Permit - Jabi District", type: "BUILDING_PLAN" as const, regulatoryBody: "FCDA", status: "INSPECTION_SCHEDULED" as const, currentStep: 6, totalSteps: 7, totalFeeKobo: 65000000, paidFeeKobo: 55000000, submittedAt: "2024-02-10" },
  { id: "p4", reference: "AGIS-2024-0567", title: "C of O Application - Maitama", type: "CERTIFICATE_OF_OCCUPANCY" as const, regulatoryBody: "AGIS", status: "UNDER_REVIEW" as const, currentStep: 3, totalSteps: 8, totalFeeKobo: 120000000, paidFeeKobo: 50000000, submittedAt: "2024-01-20" },
  { id: "p5", reference: "LASBCA-2024-0923", title: "Development Permit - GRA Ikeja", type: "DEVELOPMENT" as const, regulatoryBody: "LASBCA", status: "APPROVED" as const, currentStep: 7, totalSteps: 7, totalFeeKobo: 85000000, paidFeeKobo: 85000000, submittedAt: "2023-11-05" },
];

export const mockDefects = [
  { id: "d1", reference: "DEF-2024-0089", title: "Roof Leak - Master Bedroom", property: "Royal Gardens Estate", unit: "Unit 7", category: "ROOFING" as const, priority: "CRITICAL" as const, status: "In Progress", reportedBy: "Mr. Ogundimu", assignedTo: "Adebayo Construction", daysOpen: 5, createdAt: "2024-05-20" },
  { id: "d2", reference: "DEF-2024-0091", title: "Hairline Cracks - External Wall", property: "Emerald City", unit: "Unit 23", category: "STRUCTURAL" as const, priority: "MEDIUM" as const, status: "Acknowledged", reportedBy: "Mrs. Adekunle", daysOpen: 12, createdAt: "2024-05-13" },
  { id: "d3", reference: "DEF-2024-0094", title: "Electrical Short - Kitchen Circuit", property: "Jabi Luxury Villas", unit: "Unit 3", category: "ELECTRICAL" as const, priority: "HIGH" as const, status: "Assigned", reportedBy: "Dr. Bello", assignedTo: "Chinedu Electrical", daysOpen: 2, createdAt: "2024-05-23" },
  { id: "d4", reference: "DEF-2024-0087", title: "Poor Drainage - Compound", property: "Royal Gardens Estate", unit: "Unit 15", category: "PLUMBING" as const, priority: "HIGH" as const, status: "In Progress", reportedBy: "Engr. Yakubu", assignedTo: "Nwosu Plumbing", daysOpen: 8, createdAt: "2024-05-17" },
  { id: "d5", reference: "DEF-2024-0082", title: "POP Ceiling Peeling", property: "Wuse Heights", unit: "Unit 8", category: "FINISHING" as const, priority: "LOW" as const, status: "Reported", reportedBy: "Mrs. Garba", daysOpen: 20, createdAt: "2024-05-05" },
  { id: "d6", reference: "DEF-2024-0093", title: "Window Seal Leak", property: "Emerald City", unit: "Unit 31", category: "FINISHING" as const, priority: "MEDIUM" as const, status: "Assigned", reportedBy: "Mr. Nwankwo", assignedTo: "Kola Aluminium", daysOpen: 6, createdAt: "2024-05-19" },
  { id: "d7", reference: "DEF-2024-0096", title: "AC Drainage Issue", property: "Royal Gardens Estate", unit: "Unit 19", category: "MEP" as const, priority: "MEDIUM" as const, status: "In Progress", reportedBy: "Dr. Okafor", assignedTo: "CoolTech Services", daysOpen: 4, createdAt: "2024-05-21" },
  { id: "d8", reference: "DEF-2024-0080", title: "Floor Tile Lifting", property: "Jabi Luxury Villas", unit: "Unit 5", category: "FINISHING" as const, priority: "LOW" as const, status: "Resolved", reportedBy: "Mrs. Mohammed", assignedTo: "Sunday Tiling", daysOpen: 15, createdAt: "2024-05-10" },
];

export const mockNotifications = [
  { id: "n1", type: "escrow", title: "Milestone Verified", message: "Milestone 3 verified for Lekki Phase 1 project", read: false, createdAt: "2 min ago" },
  { id: "n2", type: "materials", title: "Price Drop", message: "Cement prices dropped 5% in Lagos", read: false, createdAt: "1 hr ago" },
  { id: "n3", type: "quality", title: "Inspection Scheduled", message: "New inspection scheduled for Banana Island", read: false, createdAt: "3 hrs ago" },
  { id: "n4", type: "escrow", title: "Payment Released", message: "₦2,500,000 released to Adebayo Construction", read: true, createdAt: "5 hrs ago" },
  { id: "n5", type: "artisan", title: "New Rating", message: "Musa Ibrahim rated 5 stars on Lekki project", read: true, createdAt: "yesterday" },
  { id: "n6", type: "permit", title: "Permit Approved!", message: "LASBCA-2024-0923 approved", read: true, createdAt: "yesterday" },
  { id: "n7", type: "defect", title: "Defect Reported", message: "Roof leak reported at Unit 14, Royal Gardens", read: false, createdAt: "2 days ago" },
  { id: "n8", type: "estate", title: "Payment Received", message: "Dr. Ogundimu paid ₦5,000,000 for Unit 14", read: true, createdAt: "3 days ago" },
  { id: "n9", type: "materials", title: "Group Order Complete", message: "Lagos Cement Pool order confirmed - 2,000 bags", read: true, createdAt: "3 days ago" },
  { id: "n10", type: "quality", title: "Certificate Issued", message: "Quality certificate BNG-CERT-2024-0015 issued", read: true, createdAt: "1 week ago" },
];

export const mockActivities = [
  { id: "act1", module: "escrow", description: "Milestone 3 (Block Work to Lintel) verified by Engr. Kelechi Eze", project: "Lekki Phase 1 Duplex", timestamp: "2 minutes ago" },
  { id: "act2", module: "materials", description: "200 bags of Dangote Cement ordered at ₦6,500/bag", project: "Group Order #Lagos-042", timestamp: "15 minutes ago" },
  { id: "act3", module: "quality", description: "Stage 6 (MEP) inspection completed with score 94/100", project: "Banana Island Mansion", timestamp: "1 hour ago" },
  { id: "act4", module: "estate", description: "Unit 23 construction stage updated to Block Work", project: "Royal Gardens Estate", timestamp: "2 hours ago" },
  { id: "act5", module: "artisan", description: "Sunday Adeyemi (Tiler) hired for 3-week engagement", project: "VI Commercial Building", timestamp: "3 hours ago" },
  { id: "act6", module: "permit", description: "Site inspection completed by LASBCA officer", project: "Lekki Phase 1 Permit", timestamp: "5 hours ago" },
  { id: "act7", module: "defect", description: "Roof leak repair commenced at Unit 7", project: "Royal Gardens Estate", timestamp: "6 hours ago" },
  { id: "act8", module: "escrow", description: "₦3,000,000 deposited into escrow account", project: "Jabi Semi-Detached", timestamp: "8 hours ago" },
  { id: "act9", module: "quality", description: "New inspection scheduled for Foundation stage", project: "GRA Ikeja Duplex", timestamp: "yesterday" },
  { id: "act10", module: "materials", description: "Rebar prices updated - down 3.2% this week", project: "Market Update", timestamp: "yesterday" },
];
